=== colameo/whole/org.whole.test/test/org/whole/lang/xsd/parsers/datatypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema	xmlns="http://www.w3.org/2001/XMLSchema"
		xmlns:dt="http://lang.whole.org/XsdDatatypes"
		targetNamespace="http://lang.whole.org/XsdDatatypes"
		attributeFormDefault="unqualified"
		elementFormDefault="qualified">

	<!-- primitive types -->
	<element name="boolean" type="boolean"/>
	<element name="byte" type="byte"/>
	<element name="short" type="short"/>
	<element name="int" type="int"/>
	<element name="long" type="long"/>
	<element name="double" type="double"/>
	<element name="float" type="float"/>
	<!--element name="char" type="char"/-->
	<element name="string" type="string"/>

	<!-- date/time datatypes -->
	<element name="date" type="date"/>
	<element name="dateTime" type="dateTime"/>
	<element name="time" type="time"/>
	<element name="yearMonth" type="gYearMonth"/>
	<element name="duration" type="duration"/>

	<!--math types -->
	<element name="decimal" type="decimal"/>
	<element name="integer" type="integer"/>

	<group name="dataType">
		<choice>
			<element ref="dt:boolean"/>
			<element ref="dt:byte"/>
			<element ref="dt:short"/>
			<element ref="dt:int"/>
			<element ref="dt:long"/>
			<element ref="dt:double"/>
			<element ref="dt:float"/>
			<!--element ref="dt:char"/-->
			<element ref="dt:string"/>

			<element ref="dt:date"/>
			<element ref="dt:dateTime"/>
			<element ref="dt:time"/>
			<element ref="dt:yearMonth"/>
			<element ref="dt:duration"/>

			<element ref="dt:decimal"/>
			<element ref="dt:integer"/>
		</choice>
	</group>

	<complexType name="dataTypes">
		<group ref="dt:dataType" minOccurs="0" maxOccurs="unbounded"/>
	</complexType>

	<element name="dataTypes" type="dt:dataTypes"/>
</schema>

=== colameo/whole/org.whole.test/test/org/whole/lang/xsd/parsers/datatypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataTypes xmlns="http://lang.whole.org/XsdDatatypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lang.whole.org/XsdDatatypes datatypes.xsd">
	<boolean>true</boolean>
	<boolean>false</boolean>
	<byte>127</byte>
	<byte>-128</byte>
	<short>-32768</short>
	<short>32767</short>
	<int>-2147483648</int>
	<int>2147483647</int>
	<long>-9223372036854775808</long>
	<long>9223372036854775807</long>
	<float>-INF</float>
	<float>INF</float>
	<float>NaN</float>
	<float>3.14</float>
	<float>-10000.0</float>
	<float>1.26743237E15</float>
	<double>-INF</double>
	<double>INF</double>
	<double>NaN</double>
	<double>3.14</double>
	<double>-10000.0</double>
	<double>1.26743233E15</double>

	<date>1999-10-10</date>
	<dateTime>1990-11-30T12:30:43Z</dateTime>
	<time>12:30:43</time>
	<yearMonth>1990-11</yearMonth>
	<duration>P5Y</duration>

	<decimal>8347923570435095219358.73248923874</decimal>
	<integer>834792357043509521935873248923874</integer>
</dataTypes>
