=== colameo/whole/org.whole.test/test/org/whole/lang/xsd/mapping/samples/ChoiceSample.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:tns="http://lang.whole.org/MT3.001.01/" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://lang.whole.org/MT3.001.01/">

    <xs:element name="document" type="tns:Document"/>
    
    <xs:complexType name="Document">
    	<xs:sequence>
    		<xs:element name="groupHeader" type="tns:GroupHeader"/>
    		<xs:element maxOccurs="unbounded" minOccurs="0" name="messages" type="tns:MessageType"/>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="GroupHeader">
    	<xs:sequence>
    		<xs:element name="grpId" type="xs:string"/>
    		<xs:element name="currDate" type="xs:string"/>
    		<xs:element name="totAmount" type="xs:string"/>
    		<xs:element name="nOfMsgs" type="xs:int"/>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="MessageType">
    	<xs:sequence>
    		<xs:element name="id" type="xs:string"/>
    		<xs:element name="amount" type="xs:string"/>
    		<xs:element name="debitor" type="tns:DebitorType"/>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="DebitorType">
    	<xs:choice>
    		<xs:element name="bic" type="xs:string"/>
    		<xs:element name="personId" type="tns:PersonId"/>
    	</xs:choice>
    </xs:complexType>

    <xs:complexType name="PersonId">
    	<xs:sequence>
    		<xs:element name="name" type="xs:string"/>
    		<xs:element name="dateOfBirth" type="xs:string"/>
    	</xs:sequence>
    </xs:complexType>
</xs:schema>

=== colameo/whole/org.whole.test/test/org/whole/lang/xsd/mapping/samples/ChoiceSample.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://lang.whole.org/MT3.001.01/"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://lang.whole.org/MT3.001.01/ ChoiceSample.xsd">

    <groupHeader>
        <grpId>ID:001</grpId>
        <currDate>23/10/2008</currDate>
        <totAmount>1000.00</totAmount>
        <nOfMsgs>2</nOfMsgs>
    </groupHeader>
    <messages>
        <id>ID:002</id>
        <amount>500.50</amount>
        <debitor>
        	<bic>ABNANAL02XX</bic>
        </debitor>
    </messages>
    <messages>
        <id>ID:003</id>
        <amount>499.50</amount>
        <debitor>
	        <bic>ABNANAL02XX</bic>
        </debitor>
    </messages>
</document>
