=== colameo/whole/org.whole.test/test/org/whole/lang/xsd/mapping/samples/Editors.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://lang.whole.org/Editors" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://lang.whole.org/Editors" elementFormDefault="qualified">
    <xsd:element name="editor" type="Editor"/>
    <xsd:complexType name="Editor">
        <xsd:sequence>
            <xsd:group ref="EditorName"/>
            <xsd:group minOccurs="0" ref="EditorName"/>
            <xsd:element ref="modelComponent"/>
            <xsd:element ref="viewComponent"/>
            <xsd:element ref="controllerComponent"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="modelComponent" type="ModelComponent"/>
    <xsd:complexType name="ModelComponent">
        <xsd:sequence>
            <xsd:group ref="ModelName"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="controllerComponent" type="ControllerComponent"/>
    <xsd:complexType name="ControllerComponent">
        <xsd:sequence>
            <xsd:element name="declarations" type="ControllerDeclarations"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="controllerDeclarations" type="ControllerDeclarations"/>
    <xsd:complexType name="ControllerDeclarations">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:group ref="ControllerDeclaration"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="partDeclaration" type="PartDeclaration"/>
    <xsd:complexType name="PartDeclaration">
        <xsd:sequence>
            <xsd:group ref="PartName"/>
            <xsd:group ref="EntityName"/>
            <xsd:group ref="FigureName"/>
            <xsd:element ref="entityFeatures"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="javaPartDeclaration" type="JavaPartDeclaration"/>
    <xsd:complexType name="JavaPartDeclaration">
        <xsd:sequence>
            <xsd:group ref="PartName"/>
            <xsd:element ref="entityNames"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="genericPartDeclaration" type="GenericPartDeclaration"/>
    <xsd:complexType name="GenericPartDeclaration">
        <xsd:sequence>
            <xsd:element name="partName" type="GenericPartName"/>
            <xsd:element ref="entityNames"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="entityFeatures" type="EntityFeatures"/>
    <xsd:complexType name="EntityFeatures">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:group ref="FeatureName"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="genericPartName" type="GenericPartName"/>
    <xsd:simpleType name="GenericPartName">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="CompositeColumn"/>
            <xsd:enumeration value="CompositeRow"/>
            <xsd:enumeration value="ConstructorColumn"/>
            <xsd:enumeration value="ConstructorRow"/>
            <xsd:enumeration value="FoldableConstructor"/>
            <xsd:enumeration value="Resolver"/>
            <xsd:enumeration value="OptionalResolver"/>
            <xsd:enumeration value="LiteralData"/>
            <xsd:enumeration value="KeywordData"/>
            <xsd:enumeration value="IdentifierData"/>
            <xsd:enumeration value="OperatorData"/>
            <xsd:enumeration value="DelimiterData"/>
            <xsd:enumeration value="ParenthesisData"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:element name="viewComponent" type="ViewComponent"/>
    <xsd:complexType name="ViewComponent">
        <xsd:sequence>
            <xsd:element name="declarations" type="ViewDeclarations"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="viewDeclarations" type="ViewDeclarations"/>
    <xsd:complexType name="ViewDeclarations">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:group ref="ViewDeclaration"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="simpleFigureDeclaration" type="SimpleFigureDeclaration"/>
    <xsd:complexType name="SimpleFigureDeclaration">
        <xsd:sequence>
            <xsd:group ref="FigureName"/>
            <xsd:group ref="FigureBody"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="foldableTextualFigure" type="FoldableTextualFigure"/>
    <xsd:complexType name="FoldableTextualFigure">
        <xsd:sequence>
            <xsd:element name="expandedFigure" type="TextualFigure"/>
            <xsd:element name="collapsedFigure" type="TextualFigure"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="textualFigure" type="TextualFigure"/>
    <xsd:complexType name="TextualFigure">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="row"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="row" type="Row"/>
    <xsd:complexType name="Row">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:group ref="RowElement"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="childPlace" type="ChildPlace"/>
    <xsd:complexType name="ChildPlace">
        <xsd:sequence/>
    </xsd:complexType>
    <xsd:element name="indent" type="Indent"/>
    <xsd:complexType name="Indent">
        <xsd:sequence/>
    </xsd:complexType>
    <xsd:element name="foldingToggle" type="FoldingToggle"/>
    <xsd:complexType name="FoldingToggle">
        <xsd:sequence/>
    </xsd:complexType>
    <xsd:element name="keywordToken" type="KeywordToken"/>
    <xsd:simpleType name="KeywordToken">
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>
    <xsd:element name="literalToken" type="LiteralToken"/>
    <xsd:simpleType name="LiteralToken">
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>
    <xsd:element name="identifierToken" type="IdentifierToken"/>
    <xsd:simpleType name="IdentifierToken">
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>
    <xsd:element name="operatorToken" type="OperatorToken"/>
    <xsd:simpleType name="OperatorToken">
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>
    <xsd:element name="delimiterToken" type="DelimiterToken"/>
    <xsd:simpleType name="DelimiterToken">
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>
    <xsd:element name="parenthesisToken" type="ParenthesisToken"/>
    <xsd:simpleType name="ParenthesisToken">
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>
    <xsd:element name="entityNames" type="EntityNames"/>
    <xsd:complexType name="EntityNames">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:group ref="EntityName"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="identifier" type="Identifier"/>
    <xsd:simpleType name="Identifier">
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>
    <xsd:group name="EntityName">
        <xsd:choice>
            <xsd:element ref="identifier"/>
        </xsd:choice>
    </xsd:group>
    <xsd:group name="EditorName">
        <xsd:choice>
            <xsd:element ref="identifier"/>
        </xsd:choice>
    </xsd:group>
    <xsd:group name="FigureName">
        <xsd:choice>
            <xsd:element ref="identifier"/>
        </xsd:choice>
    </xsd:group>
    <xsd:group name="ViewDeclaration">
        <xsd:choice>
            <xsd:element ref="simpleFigureDeclaration"/>
        </xsd:choice>
    </xsd:group>
    <xsd:group name="ModelName">
        <xsd:choice>
            <xsd:element ref="identifier"/>
        </xsd:choice>
    </xsd:group>
    <xsd:group name="ControllerDeclaration">
        <xsd:choice>
            <xsd:element ref="partDeclaration"/>
            <xsd:element ref="javaPartDeclaration"/>
            <xsd:element ref="genericPartDeclaration"/>
        </xsd:choice>
    </xsd:group>
    <xsd:group name="FeatureName">
        <xsd:choice>
            <xsd:element ref="identifier"/>
        </xsd:choice>
    </xsd:group>
    <xsd:group name="PartName">
        <xsd:choice>
            <xsd:element ref="identifier"/>
        </xsd:choice>
    </xsd:group>
    <xsd:group name="FigureBody">
        <xsd:choice>
            <xsd:element ref="foldableTextualFigure"/>
            <xsd:element ref="textualFigure"/>
        </xsd:choice>
    </xsd:group>
    <xsd:group name="RowElement">
        <xsd:choice>
            <xsd:element ref="childPlace"/>
            <xsd:element ref="indent"/>
            <xsd:element ref="foldingToggle"/>
            <xsd:element ref="keywordToken"/>
            <xsd:element ref="literalToken"/>
            <xsd:element ref="identifierToken"/>
            <xsd:element ref="operatorToken"/>
            <xsd:element ref="delimiterToken"/>
            <xsd:element ref="parenthesisToken"/>
        </xsd:choice>
    </xsd:group>
</xsd:schema>

=== colameo/whole/org.whole.test/test/org/whole/lang/xsd/mapping/samples/Editors.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xmlns="http://lang.whole.org/Editors" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lang.whole.org/Editors Editors.xsd">
    <identifier>FirstOrderLogicTextual</identifier>
    <modelComponent>
        <identifier>FirstOrderLogic</identifier>
    </modelComponent>
    <viewComponent>
        <declarations>
            <simpleFigureDeclaration>
                <identifier>TheoryFigure</identifier>
                <foldableTextualFigure>
                    <expandedFigure>
                        <row>
                            <keywordToken>theory</keywordToken>
                            <childPlace/>
                            <foldingToggle/>
                        </row>
                        <row>
                            <indent/>
                            <childPlace/>
                        </row>
                        <row>
                            <indent/>
                            <keywordToken>declarations</keywordToken>
                        </row>
                        <row>
                            <indent/>
                            <indent/>
                            <childPlace/>
                        </row>
                        <row>
                            <indent/>
                            <keywordToken>assertions</keywordToken>
                        </row>
                        <row>
                            <indent/>
                            <indent/>
                            <childPlace/>
                        </row>
                    </expandedFigure>
                    <collapsedFigure>
                        <row>
                            <keywordToken>theory</keywordToken>
                            <childPlace/>
                            <foldingToggle/>
                        </row>
                    </collapsedFigure>
                </foldableTextualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>ImportDeclarationFigure</identifier>
                <textualFigure>
                    <row>
                        <keywordToken>import</keywordToken>
                        <childPlace/>
                        <keywordToken>as</keywordToken>
                        <childPlace/>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>EqualityPredicateApplicationFigure</identifier>
                <textualFigure>
                    <row>
                        <childPlace/>
                        <operatorToken>=</operatorToken>
                        <childPlace/>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>SubtypeDeclarationFigure</identifier>
                <textualFigure>
                    <row>
                        <childPlace/>
                        <operatorToken>&lt;=</operatorToken>
                        <childPlace/>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>NameDeclarationFigure</identifier>
                <textualFigure>
                    <row>
                        <childPlace/>
                        <operatorToken>:</operatorToken>
                        <childPlace/>
                        <indent/>
                        <parenthesisToken>{</parenthesisToken>
                        <childPlace/>
                        <parenthesisToken>}</parenthesisToken>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>SortTypeFigure</identifier>
                <textualFigure>
                    <row>
                        <keywordToken>sort</keywordToken>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>VariableTypeFigure</identifier>
                <textualFigure>
                    <row>
                        <childPlace/>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>FunctionTypeFigure</identifier>
                <textualFigure>
                    <row>
                        <parenthesisToken>(</parenthesisToken>
                        <childPlace/>
                        <parenthesisToken>)</parenthesisToken>
                        <operatorToken>-&gt;</operatorToken>
                        <childPlace/>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>PredicateTypeFigure</identifier>
                <textualFigure>
                    <row>
                        <parenthesisToken>(</parenthesisToken>
                        <childPlace/>
                        <parenthesisToken>)</parenthesisToken>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>VariableDeclarationFigure</identifier>
                <textualFigure>
                    <row>
                        <childPlace/>
                        <operatorToken>:</operatorToken>
                        <childPlace/>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>ExistUniqueFigure</identifier>
                <textualFigure>
                    <row>
                        <keywordToken>?!</keywordToken>
                        <parenthesisToken>(</parenthesisToken>
                        <childPlace/>
                        <parenthesisToken>)</parenthesisToken>
                        <childPlace/>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>QualifiedNameFigure</identifier>
                <textualFigure>
                    <row>
                        <childPlace/>
                        <operatorToken>.</operatorToken>
                        <childPlace/>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>FeatureNameFigure</identifier>
                <textualFigure>
                    <row>
                        <childPlace/>
                        <operatorToken>.</operatorToken>
                        <childPlace/>
                        <operatorToken>.</operatorToken>
                        <childPlace/>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>PredicateFigure</identifier>
                <textualFigure>
                    <row>
                        <keywordToken>predicate</keywordToken>
                        <childPlace/>
                        <parenthesisToken>(</parenthesisToken>
                        <childPlace/>
                        <parenthesisToken>)</parenthesisToken>
                        <delimiterToken>:</delimiterToken>
                        <childPlace/>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>FunctionFigure</identifier>
                <textualFigure>
                    <row>
                        <keywordToken>function</keywordToken>
                        <childPlace/>
                        <parenthesisToken>(</parenthesisToken>
                        <childPlace/>
                        <parenthesisToken>)</parenthesisToken>
                        <delimiterToken>:</delimiterToken>
                        <childPlace/>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>AxiomFigure</identifier>
                <textualFigure>
                    <row>
                        <keywordToken>axiom</keywordToken>
                        <childPlace/>
                        <delimiterToken>:</delimiterToken>
                        <childPlace/>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>TheoremFigure</identifier>
                <textualFigure>
                    <row>
                        <keywordToken>theorem</keywordToken>
                        <childPlace/>
                        <delimiterToken>:</delimiterToken>
                        <childPlace/>
                    </row>
                    <row>
                        <indent/>
                        <childPlace/>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
            <simpleFigureDeclaration>
                <identifier>ApplicationFigure</identifier>
                <textualFigure>
                    <row>
                        <childPlace/>
                        <parenthesisToken>(</parenthesisToken>
                        <childPlace/>
                        <parenthesisToken>)</parenthesisToken>
                    </row>
                </textualFigure>
            </simpleFigureDeclaration>
        </declarations>
    </viewComponent>
    <controllerComponent>
        <declarations>
            <partDeclaration>
